// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjcpzzgitvpmqvnmfejd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqY3B6emdpdHZwbXF2bm1mZWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTYwNDUsImV4cCI6MjA2NDAzMjA0NX0.opxTQ8Y49-o6AGMo2T4Vyxf4iOLi3rImI0EQD13w-hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);